#!/bin/bash

#set -e

PP=$(dirname $0)

source $PP/lib.bash

source_conf
ask_init

GRANT_DEF="$(defgrant)"
TCLB_DEF="$(pwd)"
CONFOPT_DEF="--disable-cuda"
RHOME_DEF=$(R RHOME 2>/dev/null)

source_cluster

ask GRANT "What is your grant name"

if [ -z "$GRANT" ]
then
	echo No grant provided.
	exit -1
fi

if ! checkgrant $GRANT
then
	echo No such grant: $GRANT
	exit -1
fi

ask TCLB "What is the path to TCLB" path

if [ ! -d "$TCLB/src" ]
then
	echo there is no src subdirectory - something is wrong
	echo file not found: $TCLB/src
	exit -1;
else
	TCLB=$(cd $TCLB; pwd)
fi

PROGENV_l=$(module list 2>&1 | grep PrgEnv | sed 's/^.*) //') #Getting the PrgEnv module loaded now.
[ -z "$PROGENV" ] && PROGENV="$PROGENV_l"
echo -n "What PrgEnv you want to use [$PROGENV]: "
read PROGENV_n
[ ! -z "$PROGENV_n" ] && PROGENV="$PROGENV_n"

if [ -z "$(module av $PROGENV 2>&1)" ]
then
	echo there is no module $PROGENV
	exit -1;
fi

LOAD="$LOAD $PROGENV"
UNLOAD="$UNLOAD $PROGENV_l"

ask CONFOPT "Provide ./configure options you want to use (please use single ' for quotes)"

ask RHOME "What is the path to R (without the bin/ part)"

if -z "$RHOME_ASK"
then
	if [ ! -f "$RHOME/bin/R" ]
	then
		echo R not found in $RHOME/bin/
		exit -1;
	fi
fi

ask DEBUGQ "What is the name of the debug queue/partition"
ask MAINQ "What is the name of the main queue/partition to use"
ask LOAD "What modules to load"
ask UNLOAD "What modules to unload first"

for i in $LOAD $UNLOAD
do
	if [ -z "$(module av $i 2>&1)" ]
	then
		echo there is no module $i
		exit -1;
	fi
done
	

save_conf

cat >$PP/mods.ini <<EOF
module unload $UNLOAD
module load $LOAD
$([ -z "$RHOME" ] || echo "export PATH=\"$RHOME/bin:\$PATH\"")

if ! declare -f pb_msg >/dev/null
then
	function pb_msg { return 0; }
	function pb_file { return 0; }
else
	PB_CURL_OPT="--insecure"
fi

function say {
	MSG="\$@"
	pb_msg "\$SLURM_JOB_NAME" "\$MSG (after \$SECONDS s)"
}
EOF

if ask_no "Do you want to install needed R packages now?"
then
	salloc -p $DEBUGQ --ntasks=1 $PP/exec.install skipssl rdep
fi

if ask_yes "Do you want to run ./configure now?"
then
	salloc -p $DEBUGQ --ntasks=1 $PP/exec.configure $CONFOPT
fi
