#!/bin/bash

PP=$(dirname $0)
[ -f $PP/conf.ini ] || $PP/config
[ -f $PP/conf.ini ] || exit -1
. $PP/conf.ini	

if [ -z "$1" ] || [ -z "$2" ]
then
	echo Usage: ./run MODEL CASE.xml [cores]
	exit -1
fi

MODEL=$1
shift
CASE=$1
shift
CPUS=$1
shift

if [ -z "$CPUS" ]
then
	CPUS=1
fi

echo Trying to run $CASE with $MODEL model on $CPUS cores...

if [ $CPUS -gt 24 ]
then
	PPN=24
	NODES=$[$CPUS/24]
else
	PPN=$CPUS
	NODES=1
fi

if [ $CPUS -ne $[$NODES*$PPN] ]
then
	echo Requested number of CPUS \($CPUS\) is not $NODES x $PPN
	exit -1
fi

if [ ! -f "$CASE" ]
then
	echo No case file: $CASE
	exit -1
fi

NAME=CLB:$CASE
NCPU=$CPUS

SOLVER=$TCLB/CLB/$MODEL/main

if [ ! -f "$SOLVER" ]
then
	echo No such model: $MODEL
	echo File not found: $SOLVER
	exit -1
fi

sbatch "$@" <<EOF
#!/bin/bash -l
#SBATCH -J $NAME
#SBATCH -N $NODES
#SBATCH -n $NCPU
#SBATCH --ntasks-per-node=$PPN
#SBATCH --time=01:00:00 
#SBATCH -A $GRANT
#SBATCH -p workq
 
     cd \$SLURM_SUBMIT_DIR 
echo "###### Nodes:          #######"
     srun /bin/hostname
echo "###### Loading modules #######"
	source $PP/conf.ini
	mod_add=false
	source $PP/mods.ini
echo "###### --------------- #######"
echo ""
	trap "say Errored" ERR
	trap "say Terminated" TERM
	trap "say Killed" KILL
	set -e
	say Started
	srun $SOLVER $CASE
	say Finished
EOF
