#!/bin/bash

PP=$(dirname $0)
[ -f $PP/conf.ini ] || $PP/config
[ -f $PP/conf.ini ] || exit -1
. $PP/conf.ini	
. $PP/lib.bash

MODEL=$1
shift
CASE=$1
shift
UNITS=$1
shift

if [ -z "$MODEL" ] || [ -z "$CASE" ]
then
	echo Usage: ./run MODEL CASE.xml [cores]
	exit -1
fi

if [ ! -f "$CASE" ]
then
	echo No case file: $CASE
	exit -1
fi

SOLVER=$TCLB/CLB/$MODEL/main

if [ ! -f "$SOLVER" ]
then
	echo No such model: $MODEL
	echo File not found: $SOLVER
	exit -1
fi


if [ -z "$UNITS" ]
then
	UNITS=1
fi

if [ $UNITS -gt $MAX_UNITS_PER_NODE ]
then
	UNITS_PER_NODE=$MAX_UNITS_PER_NODE
	NODES=$[$UNITS/$UNITS_PER_NODE]
	CORES_PER_UNIT=$CORES_PER_UNIT_FULL
else
	UNITS_PER_NODE=$UNITS
	NODES=1
fi


if [ $UNITS -ne $[$NODES*$UNITS_PER_NODE] ]
then
	echo Requested number of cores/gpus \($UNITS\) is not $NODES x $UNITS_PER_NODE
	exit -1
fi

CORES=$[$UNITS*$CORES_PER_UNIT]

echo "Trying to run $CASE with $MODEL model on $UNITS cores/gpus ($NODES x $UNITS_PER_NODE x $CORES_PER_UNIT)..."

NAME=CLB:$CASE

if test "$RUN_GPU" == "y"
then
	GPU_HEADER="#SBATCH --gres=gpu:$UNITS_PER_NODE"
fi

sbatch $(arg -A $GRANT) $(arg -p $MAINQ) "$@" <<EOF
#!/bin/bash -l
#SBATCH -J $NAME
#SBATCH -N $NODES
#SBATCH -n $UNITS
#SBATCH -c $CORES_PER_UNIT
#SBATCH --ntasks-per-node=$UNITS_PER_NODE
#SBATCH --time=01:00:00 
$GPU_HEADER
 
     cd \$SLURM_SUBMIT_DIR 
echo "###### Nodes:          #######"
     srun /bin/hostname
echo "###### Loading modules #######"
	source $PP/conf.ini
	mod_add=false
	source $PP/mods.ini RUN
echo "###### --------------- #######"
echo ""
	trap "say Errored" ERR
	trap "say Terminated" TERM
	trap "say Killed" KILL
	set -e
	say Started
	$RUN_COMMAND $SOLVER $CASE
	say Finished
EOF
